# Generated by Django 4.2.5 on 2023-10-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
    ]
